apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ephemeral-environment-pipeline
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: ephemeral-environment-pipeline-run-
    spec:
      serviceAccountName: tekton-triggers-example-sa
      pipelineRef:
        name: ephemeral-environment-pipeline
      params:
      - name: message
        value: $(params.message)
      - name: contenttype
        value: $(params.contenttype)
      resources:
      - name: git-source
        resourceSpec:
          type: git
          params:
          - name: url
            value: $(params.gitrepositoryurl)
          - name: revision
            value: $(params.gitrevision)
      - name: docker-image
        resourceSpec:
          type: image
          params:
          - name: url
            value: gcr.io/basictoy/elementaltoy-ephemeral
