apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: test-run2
spec:
  serviceAccountName: posinaga-demo-github-git-ssh
  taskRef:
    name: kaniko
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/posinaga-demo/basictoy 
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: gcr.io/test-kaniko-task/basictoy
