apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-example-binding
subjects:
- kind: ServiceAccount
  name: triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triggers-role